// const botao = document.querySelector('button')

// botao.onclick = function() {
//     console.log('Botao clicando via propriedade')
// }

// function saudacao(){
//     console.log("Olá")
// }

// botao.addEventListener('click', saudacao)
// botao.addEventListener('click', () => console.log('Segunda função executada'))



// function soma(a,b=4){return a+b}

// const resultado = soma(2,2)

// console.log(resultado)

// const x = function(a, b){ return a+b}

// const dobrar = (n) => n * 2

